version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app.docker
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - devnet

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - devnet

volumes:
  postgres-data:

networks:
  devnet:
